
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.12.35527.113 d17.12
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WiseBlog.API", "WiseBlog.API.csproj", "{3908AA6D-4722-41DD-BCC5-F1E0B2EAF217}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WiseBlog.Shared", "..\WiseBlog.Shared\WiseBlog.Shared.csproj", "{8903C820-9401-45FA-94CE-921840543B72}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{3908AA6D-4722-41DD-BCC5-F1E0B2EAF217}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{3908AA6D-4722-41DD-BCC5-F1E0B2EAF217}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{3908AA6D-4722-41DD-BCC5-F1E0B2EAF217}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{3908AA6D-4722-41DD-BCC5-F1E0B2EAF217}.Release|Any CPU.Build.0 = Release|Any CPU
		{8903C820-9401-45FA-94CE-921840543B72}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{8903C820-9401-45FA-94CE-921840543B72}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{8903C820-9401-45FA-94CE-921840543B72}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{8903C820-9401-45FA-94CE-921840543B72}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
